// Code generated by protoc-gen-go-json. DO NOT EDIT.
package example

import (
	"bytes"
	"io"
	"github.com/golang/protobuf/jsonpb"
)

func (p *Hello) MarshalJSON() ([]byte, error) {
	var bytes bytes.Buffer
	err := (&jsonpb.Marshaler{}).Marshal(io.Writer(&bytes), p)
	return bytes.Bytes(), err
}

func (p *Hello) UnmarshalJSON(data []byte) error {
	return jsonpb.Unmarshal(bytes.NewBuffer(data), p)
}
